### ISSUE TITLE
Public folder still accessible

### ISSUE THREAD

**Issue by timstrasser** [kgierke/nuxt-basic-auth#3]
Hello, so far this module works great! I was wondering if it would be possible to also protect the contents of the “public” folder, as they are still accessible without logging in.

**Comment by kgierke** [comment]
Hi, sorry for taking so long to reply. After looking into it, it seems to me like there's no easy or obvious way in doing so, since the public directory gets handled without involving any server middleware registered through a Nuxt plugin. So as of now I don't see the possibility to add this feature sorry.

Feel free to re-open this issue if you have any hints or examples of how to achieve this.
